# Generated by Django 2.0.10 on 2019-07-16 23:11

import blt_hr_system.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('expiration_yrs', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doc_read_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doc_submit_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee_absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('yr1', models.PositiveIntegerField(default=0)),
                ('yr1_num_days', models.PositiveIntegerField(default=0)),
                ('yr2', models.PositiveIntegerField(default=0)),
                ('yr2_num_days', models.PositiveIntegerField(default=0)),
                ('num_days_prior_apr_31', models.PositiveIntegerField(default=0)),
                ('absence_type', models.CharField(choices=[('Sick', 'Sick'), ('Vacation', 'Vacation'), ('Bereavement', 'Bereavement'), ('Time off without pay', 'Time off without pay'), ('Maternity or Paternity', 'Maternity or Paternity'), ('Other', 'Other')], max_length=200)),
                ('absence_reason', models.CharField(max_length=1000)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('is_manager_approved', models.BooleanField(default=False)),
                ('is_admin_approved', models.BooleanField(default=False)),
                ('date_approved_manager', models.DateField()),
                ('date_approved_admin', models.DateField()),
                ('manager_comment', models.CharField(blank=True, max_length=1000)),
                ('admin_comment', models.CharField(blank=True, max_length=1000)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee_certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acq_date', models.DateField()),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('upload', models.FileField(upload_to=blt_hr_system.models.cert_doc_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('cert_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.certification')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.ManyToManyField(to='blt_hr_system.company_info')),
            ],
        ),
        migrations.CreateModel(
            name='hourly_timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='onboarding_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('office_staff', models.BooleanField(default=False)),
                ('certs', models.ManyToManyField(to='blt_hr_system.certification')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.company_info')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.Profile')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sage_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=200)),
                ('job_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='timesheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='training_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_name', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to=blt_hr_system.models.RandomFileName('media/training_docs/'))),
                ('active_doc', models.BooleanField(default=False)),
                ('onboarding_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.onboarding_cat')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vaction_allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloc_absence_days', models.PositiveIntegerField(default=0)),
                ('carr_over_days', models.PositiveIntegerField(default=0)),
                ('yr', models.PositiveIntegerField(default=0)),
                ('is_increased', models.BooleanField(default=False)),
                ('increased_days', models.PositiveIntegerField(default=0, null=True)),
                ('increased_date', models.DateField(null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hourly_timesheet',
            name='sage_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.sage_jobs'),
        ),
        migrations.AddField(
            model_name='doc_submit_req',
            name='onboarding_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.onboarding_cat'),
        ),
        migrations.AddField(
            model_name='doc_submit_req',
            name='submitted',
            field=models.ManyToManyField(to='blt_hr_system.training_docs'),
        ),
        migrations.AddField(
            model_name='doc_read_req',
            name='onboarding_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.onboarding_cat'),
        ),
        migrations.AddField(
            model_name='doc_read_req',
            name='read',
            field=models.ManyToManyField(to='blt_hr_system.training_docs'),
        ),
    ]
