# Generated by Django 2.0.8 on 2018-12-01 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cert_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employee_absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('yr1', models.PositiveIntegerField(default=0)),
                ('yr1_num_days', models.PositiveIntegerField(default=0)),
                ('yr2', models.PositiveIntegerField(default=0)),
                ('yr2_num_days', models.PositiveIntegerField(default=0)),
                ('num_days_prior_apr_31', models.PositiveIntegerField(default=0)),
                ('absence_type', models.CharField(choices=[('Sick', 'Sick'), ('Vacation', 'Vacation'), ('Bereavement', 'Bereavement'), ('Time off without pay', 'Time off without pay'), ('Maternity or Paternity', 'Maternity or Paternity'), ('Other', 'Other')], max_length=200)),
                ('absence_reason', models.CharField(max_length=1000)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('is_manager_approved', models.BooleanField(default=False)),
                ('date_approved', models.DateField()),
                ('manager_comment', models.CharField(max_length=1000)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee_certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('acq_date', models.DateField()),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('cert_doc', models.CharField(max_length=500)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('cert_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.certification')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('group_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('region', models.ManyToManyField(to='blt_hr_system.company_info')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('employee_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.employee_group')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='training_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_name', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vaction_allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alloc_absence_days', models.PositiveIntegerField(default=0)),
                ('carr_over_days', models.PositiveIntegerField(default=0)),
                ('yr', models.PositiveIntegerField(default=0)),
                ('is_increased', models.BooleanField(default=False)),
                ('increased_days', models.PositiveIntegerField(default=0, null=True)),
                ('increased_date', models.DateField(null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cert_group',
            name='cert_req',
            field=models.ManyToManyField(help_text='Select a required certification for this group', to='blt_hr_system.certification'),
        ),
        migrations.AddField(
            model_name='cert_group',
            name='employee_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.employee_group'),
        ),
    ]
