# Generated by Django 2.0.8 on 2019-02-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='office_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doc_read_req',
            name='read',
            field=models.ManyToManyField(null=True, to='blt_hr_system.training_docs'),
        ),
        migrations.AlterField(
            model_name='doc_submit_req',
            name='submitted',
            field=models.ManyToManyField(null=True, to='blt_hr_system.training_docs'),
        ),
        migrations.AlterField(
            model_name='training_docs',
            name='active_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training_docs',
            name='onboarding_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.onboarding_cat'),
        ),
    ]
