# Generated by Django 2.0.8 on 2018-12-01 06:35

import blt_hr_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0002_auto_20181201_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_docs',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=blt_hr_system.models.RandomFileName('media/training_docs/')),
        ),
    ]
