# Generated by Django 2.2.3 on 2019-07-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0002_auto_20190719_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_holidays',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.company_info'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='holiday',
        ),
    ]
