# Generated by Django 2.2.3 on 2019-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0003_auto_20190719_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='control_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_cntrl_date', models.DateField()),
            ],
        ),
    ]
