# Generated by Django 2.0.8 on 2018-11-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0003_auto_20181104_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
