# Generated by Django 2.0.8 on 2018-12-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0004_auto_20181202_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='certs_maintained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cert_group',
            name='cert_req',
        ),
        migrations.RemoveField(
            model_name='cert_group',
            name='employee_group',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='url',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='employee_group',
            name='group_description',
        ),
        migrations.RemoveField(
            model_name='employee_group',
            name='manager',
        ),
        migrations.AddField(
            model_name='certification',
            name='expiration_yrs',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee_group',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.company_info'),
        ),
        migrations.DeleteModel(
            name='cert_group',
        ),
        migrations.AddField(
            model_name='certs_maintained',
            name='certification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.certification'),
        ),
        migrations.AddField(
            model_name='certs_maintained',
            name='employee_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.employee_group'),
        ),
    ]
