# Generated by Django 2.0.8 on 2018-11-18 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blt_hr_system', '0004_training_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_docs',
            name='upload_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training_docs',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training_docs',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media/training_docs/'),
        ),
    ]
