# Generated by Django 2.0.8 on 2018-11-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0005_auto_20181117_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_docs',
            name='upload_name',
        ),
        migrations.RemoveField(
            model_name='training_docs',
            name='uploaded_by',
        ),
    ]
