# Generated by Django 2.2.3 on 2019-07-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0006_company_holidays_upload_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='control_date',
        ),
    ]
