# Generated by Django 2.2.3 on 2019-07-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0007_delete_control_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_docs',
            name='active_doc',
        ),
    ]
