# Generated by Django 2.0.8 on 2018-12-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0008_auto_20181207_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certs_maintained',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='certs_maintained',
            name='employee_group',
        ),
        migrations.RemoveField(
            model_name='certs_maintained',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employee_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='certs',
            field=models.ManyToManyField(to='blt_hr_system.certification'),
        ),
        migrations.DeleteModel(
            name='certs_maintained',
        ),
        migrations.DeleteModel(
            name='employee_group',
        ),
    ]
