# Generated by Django 2.2.3 on 2019-07-21 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blt_hr_system', '0008_remove_training_docs_active_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.training_docs')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='doc_submit_req',
            name='onboarding_cat',
        ),
        migrations.RemoveField(
            model_name='doc_submit_req',
            name='submitted',
        ),
        migrations.AddField(
            model_name='doc_submit_req',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.training_docs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_req',
            field=models.ManyToManyField(related_name='_profile_read_req_+', to='blt_hr_system.onboarding_cat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='submit_req',
            field=models.ManyToManyField(related_name='_profile_submit_req_+', to='blt_hr_system.onboarding_cat'),
        ),
        migrations.DeleteModel(
            name='doc_read_req',
        ),
    ]
