# Generated by Django 2.0.8 on 2018-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0009_auto_20181219_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
