# Generated by Django 2.0.8 on 2018-12-19 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0011_remove_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.company_info'),
        ),
    ]
