# Generated by Django 2.2.3 on 2019-07-23 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0011_auto_20190723_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_perf_forms',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perf_forms',
            name='perf_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.perf_cat'),
        ),
    ]
