# Generated by Django 2.2.3 on 2019-07-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0012_auto_20190723_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timesheets',
        ),
        migrations.AddField(
            model_name='hourly_timesheet',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourly_timesheet',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourly_timesheet',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
