# Generated by Django 2.0.8 on 2018-12-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0013_remove_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_certification',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='employee_certification',
            name='date_submitted',
        ),
    ]
