# Generated by Django 2.2.3 on 2019-07-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0016_auto_20190724_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly_timesheet',
            name='ts_period',
            field=models.CharField(choices=[(1, 'Jul 01 2019 to Jul 14 2019'), (2, 'Jul 15 2019 to Jul 28 2019'), (3, 'Jul 29 2019 to Aug 11 2019'), (4, 'Aug 12 2019 to Aug 25 2019'), (5, 'Aug 26 2019 to Sep 08 2019'), (6, 'Sep 09 2019 to Sep 22 2019'), (7, 'Sep 23 2019 to Oct 06 2019'), (8, 'Oct 07 2019 to Oct 20 2019'), (9, 'Oct 21 2019 to Nov 03 2019'), (10, 'Nov 04 2019 to Nov 17 2019'), (11, 'Nov 18 2019 to Dec 01 2019'), (12, 'Dec 02 2019 to Dec 15 2019'), (13, 'Dec 16 2019 to Dec 29 2019'), (14, 'Dec 30 2019 to Jan 12 2020'), (15, 'Jan 13 2020 to Jan 26 2020'), (16, 'Jan 27 2020 to Feb 09 2020'), (17, 'Feb 10 2020 to Feb 23 2020'), (18, 'Feb 24 2020 to Mar 08 2020'), (19, 'Mar 09 2020 to Mar 22 2020'), (20, 'Mar 23 2020 to Apr 05 2020'), (21, 'Apr 06 2020 to Apr 19 2020'), (22, 'Apr 20 2020 to May 03 2020'), (23, 'May 04 2020 to May 17 2020'), (24, 'May 18 2020 to May 31 2020'), (25, 'Jun 01 2020 to Jun 14 2020'), (26, 'Jun 15 2020 to Jun 28 2020'), (27, 'Jun 29 2020 to Jul 12 2020'), (28, 'Jul 13 2020 to Jul 26 2020'), (29, 'Jul 27 2020 to Aug 09 2020'), (30, 'Aug 10 2020 to Aug 23 2020'), (31, 'Aug 24 2020 to Sep 06 2020'), (32, 'Sep 07 2020 to Sep 20 2020'), (33, 'Sep 21 2020 to Oct 04 2020'), (34, 'Oct 05 2020 to Oct 18 2020'), (35, 'Oct 19 2020 to Nov 01 2020'), (36, 'Nov 02 2020 to Nov 15 2020'), (37, 'Nov 16 2020 to Nov 29 2020'), (38, 'Nov 30 2020 to Dec 13 2020'), (39, 'Dec 14 2020 to Dec 27 2020'), (40, 'Dec 28 2020 to Jan 10 2021'), (41, 'Jan 11 2021 to Jan 24 2021'), (42, 'Jan 25 2021 to Feb 07 2021'), (43, 'Feb 08 2021 to Feb 21 2021'), (44, 'Feb 22 2021 to Mar 07 2021'), (45, 'Mar 08 2021 to Mar 21 2021'), (46, 'Mar 22 2021 to Apr 04 2021'), (47, 'Apr 05 2021 to Apr 18 2021'), (48, 'Apr 19 2021 to May 02 2021'), (49, 'May 03 2021 to May 16 2021'), (50, 'May 17 2021 to May 30 2021'), (51, 'May 31 2021 to Jun 13 2021'), (52, 'Jun 14 2021 to Jun 27 2021'), (53, 'Jun 28 2021 to Jul 11 2021'), (54, 'Jul 12 2021 to Jul 25 2021'), (55, 'Jul 26 2021 to Aug 08 2021'), (56, 'Aug 09 2021 to Aug 22 2021'), (57, 'Aug 23 2021 to Sep 05 2021'), (58, 'Sep 06 2021 to Sep 19 2021'), (59, 'Sep 20 2021 to Oct 03 2021'), (60, 'Oct 04 2021 to Oct 17 2021'), (61, 'Oct 18 2021 to Oct 31 2021'), (62, 'Nov 01 2021 to Nov 14 2021'), (63, 'Nov 15 2021 to Nov 28 2021'), (64, 'Nov 29 2021 to Dec 12 2021'), (65, 'Dec 13 2021 to Dec 26 2021')], max_length=200, null=True),
        ),
    ]
