# Generated by Django 2.0.8 on 2018-12-22 19:51

import blt_hr_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0017_auto_20181222_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_certification',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=blt_hr_system.models.RandomFileName('media/certification/')),
        ),
    ]
