# Generated by Django 2.0.8 on 2018-12-23 06:47

import blt_hr_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0018_auto_20181222_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_certification',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=blt_hr_system.models.cert_doc_path),
        ),
    ]
