# Generated by Django 2.2.3 on 2019-07-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0019_auto_20190726_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_perf_forms',
            name='manager_uploaded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
