# Generated by Django 2.2.3 on 2019-07-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0020_emp_perf_forms_manager_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_perf_forms',
            name='year',
            field=models.PositiveIntegerField(choices=[(2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True),
        ),
    ]
