# Generated by Django 2.0.8 on 2019-01-06 17:38

import blt_hr_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0021_doc_read_req_doc_submit_req_onboarding_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_docs',
            name='upload',
            field=models.FileField(default=1, upload_to=blt_hr_system.models.RandomFileName('media/training_docs/')),
            preserve_default=False,
        ),
    ]
