# Generated by Django 2.2.3 on 2019-07-27 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0021_emp_perf_forms_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_perf_forms',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.Profile'),
        ),
    ]
