# Generated by Django 2.2.3 on 2019-07-29 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0022_auto_20190726_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('All', 'All'), ('Directory', 'Directory'), ('Training', 'Training'), ('Documents', 'Documents'), ('Absences', 'Absences'), ('Certifications', 'Certifications'), ('Performance', 'Performance'), ('Timesheets', 'Timesheets')], max_length=200, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blt_hr_system.Profile')),
            ],
        ),
    ]
