# Generated by Django 2.0.8 on 2019-01-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0022_auto_20190106_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_docs',
            name='upload_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
