# Generated by Django 2.0.8 on 2019-01-06 23:33

import blt_hr_system.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0023_auto_20190106_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_read_req',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.onboarding_docs'),
        ),
        migrations.AlterField(
            model_name='doc_submit_req',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.onboarding_docs'),
        ),
        migrations.AlterField(
            model_name='employee_certification',
            name='cert_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blt_hr_system.certification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_certification',
            name='upload',
            field=models.FileField(default=1, upload_to=blt_hr_system.models.cert_doc_path),
            preserve_default=False,
        ),
    ]
