# Generated by Django 2.2.3 on 2019-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0023_admin_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='control_options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('All', 'All'), ('Directory', 'Directory'), ('Training', 'Training'), ('Documents', 'Documents'), ('Absences', 'Absences'), ('Certifications', 'Certifications'), ('Performance', 'Performance'), ('Timesheets', 'Timesheets')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin_control',
            name='access_level',
        ),
        migrations.AddField(
            model_name='admin_control',
            name='access_level',
            field=models.ManyToManyField(to='blt_hr_system.control_options'),
        ),
    ]
