# Generated by Django 2.2.3 on 2019-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0024_auto_20190729_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.ManyToManyField(to='blt_hr_system.control_options'),
        ),
        migrations.DeleteModel(
            name='admin_control',
        ),
    ]
