# Generated by Django 2.2.3 on 2019-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0025_auto_20190729_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_options',
            name='access_level',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
