# Generated by Django 2.2.3 on 2019-07-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blt_hr_system', '0026_auto_20190729_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='access_level',
            new_name='access',
        ),
    ]
